/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;
import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author mateo
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salirbtn = new javax.swing.JButton();
        btnCargarAlum = new javax.swing.JButton();
        btnCargarObs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salirbtn.setForeground(new java.awt.Color(2, 3, 8));
        salirbtn.setText("Atras");
        salirbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 22, 216)));
        salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtnActionPerformed(evt);
            }
        });

        btnCargarAlum.setForeground(new java.awt.Color(11, 15, 34));
        btnCargarAlum.setText("Cargar Alumnos");
        btnCargarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarAlumActionPerformed(evt);
            }
        });

        btnCargarObs.setForeground(new java.awt.Color(20, 24, 35));
        btnCargarObs.setText("Cargar Observaciones");
        btnCargarObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarObsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ume Gothic", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 22, 26));
        jLabel1.setText("Elija que desea cargar");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 22, 216), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnCargarObs)
                .addGap(50, 50, 50)
                .addComponent(btnCargarAlum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salirbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarObs)
                    .addComponent(btnCargarAlum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(salirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtnActionPerformed
        Principal prn = new Principal();
        prn.setVisible(true);
        dispose();
    }//GEN-LAST:event_salirbtnActionPerformed

    private void btnCargarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAlumActionPerformed
        CargarAlumnos calu = new CargarAlumnos();
        calu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCargarAlumActionPerformed

    private void btnCargarObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarObsActionPerformed
        CargarObservaciones cobs = new CargarObservaciones();
        cobs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCargarObsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarAlum;
    private javax.swing.JButton btnCargarObs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salirbtn;
    // End of variables declaration//GEN-END:variables
}
